language: cpp

os: linux
dist: focal
arch: amd64

jobs:
  include:
    - compiler: gcc
      env: ENV_BUILD_TYPE=Debug VERBOSE=1
    - compiler: gcc
      env: ENV_BUILD_TYPE=Release VERBOSE=1

script: ./build.sh

notifications:
  email: false
